[package]
name = "blog_os"
version = "0.1.0"
authors = ["Alexander Dodatko <alexander.dodatko@dataart.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[package.metadata.bootimage]
default-target = "x86_64-blog_os.json"

[dependencies]
